spring:
  application:
    name: deepshuffle

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:}

spotify:
  client:
    id: ${SPOTIFY_CLIENT_ID:}
    secret: ${SPOTIFY_CLIENT_SECRET:}
  redirect-uri: ${SPOTIFY_CLIENT_URI:}
